import type { region } from '../schema/region';

type RegionSeedRow = typeof region.$inferInsert;

/**
 * 시도 17 + UNKNOWN 센티널 (§9.2, solar-8wv.15). region_code는 ISO suffix형
 * 로마자 mnemonic — 공식 명칭이 바뀌어도(강원/전북 특별자치도) 코드는 불변.
 *
 * needs-verification (solar-8wv.4 응답 샘플로 대조):
 * - kpx_region_name: 통용 축약명 초안. 실제 KPX API 응답의 지역 문자열
 *   (공백/전체명/'합계' row/세종 독립 row 여부) 확인 전까지 draft.
 * - kma_grid_x/y: 기상청 단기예보 활용가이드 격자표 초안. 시도 대표점이
 *   논쟁 가능한 값: CHUNGNAM 55/107, JEONNAM 51/67, GYEONGBUK 87/106,
 *   GYEONGGI 60/120 (도청 소재지 기준).
 * - lat/lon: 시도 대표점 근사 좌표. 발전소 좌표/시군구 확장 시 재검증.
 */
export const unknownRegionSeedRow: RegionSeedRow = {
  regionCode: 'UNKNOWN',
  regionName: '미상',
};

export const sidoRegionSeedRows: RegionSeedRow[] = [
  {
    regionCode: 'SEOUL',
    regionName: '서울특별시',
    kpxRegionName: '서울',
    kmaGridX: 60,
    kmaGridY: 127,
    lat: '37.566535',
    lon: '126.977969',
    sidoName: '서울특별시',
    sigunguName: null,
  },
  {
    regionCode: 'BUSAN',
    regionName: '부산광역시',
    kpxRegionName: '부산',
    kmaGridX: 98,
    kmaGridY: 76,
    lat: '35.179554',
    lon: '129.075642',
    sidoName: '부산광역시',
    sigunguName: null,
  },
  {
    regionCode: 'DAEGU',
    regionName: '대구광역시',
    kpxRegionName: '대구',
    kmaGridX: 89,
    kmaGridY: 90,
    lat: '35.866650',
    lon: '128.606200',
    sidoName: '대구광역시',
    sigunguName: null,
  },
  {
    regionCode: 'INCHEON',
    regionName: '인천광역시',
    kpxRegionName: '인천',
    kmaGridX: 55,
    kmaGridY: 124,
    lat: '37.456256',
    lon: '126.705206',
    sidoName: '인천광역시',
    sigunguName: null,
  },
  {
    regionCode: 'GWANGJU',
    regionName: '광주광역시',
    kpxRegionName: '광주',
    kmaGridX: 58,
    kmaGridY: 74,
    lat: '35.159545',
    lon: '126.852601',
    sidoName: '광주광역시',
    sigunguName: null,
  },
  {
    regionCode: 'DAEJEON',
    regionName: '대전광역시',
    kpxRegionName: '대전',
    kmaGridX: 67,
    kmaGridY: 100,
    lat: '36.350412',
    lon: '127.384548',
    sidoName: '대전광역시',
    sigunguName: null,
  },
  {
    regionCode: 'ULSAN',
    regionName: '울산광역시',
    kpxRegionName: '울산',
    kmaGridX: 102,
    kmaGridY: 84,
    lat: '35.538377',
    lon: '129.311360',
    sidoName: '울산광역시',
    sigunguName: null,
  },
  {
    regionCode: 'SEJONG',
    regionName: '세종특별자치시',
    kpxRegionName: '세종',
    kmaGridX: 66,
    kmaGridY: 103,
    lat: '36.480098',
    lon: '127.289037',
    sidoName: '세종특별자치시',
    sigunguName: null,
  },
  {
    regionCode: 'GYEONGGI',
    regionName: '경기도',
    kpxRegionName: '경기',
    kmaGridX: 60,
    kmaGridY: 120,
    lat: '37.275119',
    lon: '127.009466',
    sidoName: '경기도',
    sigunguName: null,
  },
  {
    regionCode: 'GANGWON',
    regionName: '강원특별자치도',
    kpxRegionName: '강원',
    kmaGridX: 73,
    kmaGridY: 134,
    lat: '37.881315',
    lon: '127.729971',
    sidoName: '강원특별자치도',
    sigunguName: null,
  },
  {
    regionCode: 'CHUNGBUK',
    regionName: '충청북도',
    kpxRegionName: '충북',
    kmaGridX: 69,
    kmaGridY: 107,
    lat: '36.635680',
    lon: '127.491384',
    sidoName: '충청북도',
    sigunguName: null,
  },
  {
    regionCode: 'CHUNGNAM',
    regionName: '충청남도',
    kpxRegionName: '충남',
    kmaGridX: 55,
    kmaGridY: 107,
    lat: '36.658826',
    lon: '126.672849',
    sidoName: '충청남도',
    sigunguName: null,
  },
  {
    regionCode: 'JEONBUK',
    regionName: '전북특별자치도',
    kpxRegionName: '전북',
    kmaGridX: 63,
    kmaGridY: 89,
    lat: '35.820196',
    lon: '127.108976',
    sidoName: '전북특별자치도',
    sigunguName: null,
  },
  {
    regionCode: 'JEONNAM',
    regionName: '전라남도',
    kpxRegionName: '전남',
    kmaGridX: 51,
    kmaGridY: 67,
    lat: '34.816084',
    lon: '126.462853',
    sidoName: '전라남도',
    sigunguName: null,
  },
  {
    regionCode: 'GYEONGBUK',
    regionName: '경상북도',
    kpxRegionName: '경북',
    kmaGridX: 87,
    kmaGridY: 106,
    lat: '36.576032',
    lon: '128.505599',
    sidoName: '경상북도',
    sigunguName: null,
  },
  {
    regionCode: 'GYEONGNAM',
    regionName: '경상남도',
    kpxRegionName: '경남',
    kmaGridX: 91,
    kmaGridY: 77,
    lat: '35.238294',
    lon: '128.692397',
    sidoName: '경상남도',
    sigunguName: null,
  },
  {
    regionCode: 'JEJU',
    regionName: '제주특별자치도',
    kpxRegionName: '제주',
    kmaGridX: 52,
    kmaGridY: 38,
    lat: '33.489011',
    lon: '126.498302',
    sidoName: '제주특별자치도',
    sigunguName: null,
  },
];

export const regionSeedRows: RegionSeedRow[] = [unknownRegionSeedRow, ...sidoRegionSeedRows];
